require("alirg.plugins-setup")

require("alirg.core.options")
require("alirg.core.keymaps")

require("alirg.plugins.comment")
require("alirg.plugins.nvim-tree")
require("alirg.plugins.lualine")
require("alirg.plugins.telescope")
require("alirg.plugins.nvim-cmp")
require("alirg.plugins.autopairs")
require("alirg.plugins.treesitter")
require("alirg.plugins.gitsigns")
require("alirg.plugins.nvim-coc")
require("alirg.plugins.nvim-test")

require("alirg.plugins.bufferline")
require("alirg.plugins.colorizer")
require("alirg.plugins.lsp-colors")
require("alirg.plugins.lspkind")
require("alirg.plugins.neosolarized")
require("alirg.plugins.ts-autotag")
require("alirg.plugins.web-devicons")
require("alirg.plugins.zen-mode")

require("alirg.plugins.lsp.mason")
require("alirg.plugins.lsp.lspsaga")
require("alirg.plugins.lsp.lspconfig")
require("alirg.plugins.lsp.null-ls")
